# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squawks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squawks_text', models.CharField(max_length=140)),
                ('squawk_time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
            options={
                'ordering': None,
            },
        ),
    ]
