# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=140)),
            ],
        ),
    ]
