# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squawkerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squawk',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
