# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squawkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squawktext',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
