# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squawkapp', '0002_auto_20161102_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squawktext',
            name='pub_date',
        ),
    ]
