# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squawker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squawker_id', models.IntegerField()),
                ('squewker_msg', models.CharField(max_length=140)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
