# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_squawker_squawker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squawker',
            old_name='squewker_msg',
            new_name='squawker_msg',
        ),
    ]
