# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squawker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squawks',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='squawks',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
    ]
