# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2016-11-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squawk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=140)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
