# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squawk',
            old_name='post',
            new_name='message',
        ),
        
    ]