# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mymessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.CharField(max_length=140)),
            ],
        ),
    ]
