# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squawker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('postdate', models.DateTimeField(verbose_name='postdate')),
            ],
        ),
    ]
