# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squawker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squawks',
            options={},
        ),
    ]
