# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=140)),
            ],
        ),
    ]
