# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post',
            new_name='message',
        ),
    ]
