# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('squawk', '0001_initial'), ('squawk', '0002_auto_20161102_0202')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squawk',
            fields=[
                ('message', models.CharField(max_length=140)),
                ('create_at', models.IntegerField(default=0)),
                ('id', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
