# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mytable',
        ),
    ]
