from django.db import models

# Create your models here.
class MyTable(models.Model):
    #id field is generated by default in Django
    timestamp = models.DateTimeField(auto_now_add=True, blank=True)
    comment = models.CharField(max_length=141)

    def __str__(self):              # __unicode__ on Python 2
        return self.comment
