# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squawk',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
